In [1]:
import pandas as pd
df=pd.read_csv("cost-of-living.csv")
print(df)

      Unnamed: 0                city      country     x1     x2     x3     x4  \
0              0               Delhi        India   4.90  22.04   4.28   1.84
1              1            Shanghai        China   5.59  40.51   5.59   1.12
2              2             Jakarta    Indonesia   2.54  22.25   3.50   2.02
3              3              Manila  Philippines   3.54  27.40   3.54   1.24
4              4               Seoul  South Korea   7.16  52.77   6.03   3.02
...          ...                 ...          ...    ...    ...    ...    ...
4869        4869        Peterborough    Australia    NaN    NaN    NaN    NaN
4870        4870          Georgetown    Australia    NaN    NaN    NaN    NaN
4871        4871  Ixtapa Zihuatanejo       Mexico   5.19  31.13  12.97   0.99
4872        4872             Iqaluit       Canada  29.78  74.61  13.77   6.70
4873        4873              Neiafu        Tonga    NaN  29.53  10.55  10.55

        x5    x6    x7  ...     x47      x48     x49      x50      x51  \
0     3.67  1.78  0.48  ...   36.26   223.87  133.38   596.16   325.82
1     4.19  3.96  0.52  ...  121.19  1080.07  564.30  2972.57  1532.23
2     3.18  2.19  0.59  ...   80.32   482.85  270.15  1117.69   584.37
3     1.90  2.91  0.93  ...   61.82   559.52  281.78  1754.40   684.81
4     4.52  3.86  1.46  ...  108.30   809.83  583.60  2621.05  1683.74
...    ...   ...   ...  ...     ...      ...     ...      ...      ...
4869   NaN   NaN   NaN  ...     NaN      NaN     NaN      NaN      NaN
4870   NaN   NaN   NaN  ...     NaN      NaN     NaN      NaN      NaN
4871   NaN  1.82  0.62  ...  103.78   415.11  259.44   518.89   415.11
4872  8.93  3.72  3.54  ...     NaN      NaN     NaN  2978.11  2978.11
4873   NaN   NaN  2.11  ...     NaN      NaN     NaN      NaN      NaN

           x52       x53      x54   x55  data_quality
0      2619.46   1068.90   586.35  7.96             1
1     17333.09   9174.88  1382.83  5.01             1
2      2694.05   1269.44   483.19  9.15             1
3      3536.04   2596.44   419.02  7.80             1
4     21847.94  10832.90  2672.23  3.47             1
...        ...       ...      ...   ...           ...
4869       NaN       NaN      NaN   NaN             0
4870       NaN       NaN      NaN   NaN             0
4871       NaN       NaN      NaN   NaN             0
4872       NaN       NaN      NaN  6.53             0
4873       NaN       NaN      NaN   NaN             0

[4874 rows x 59 columns]

In [2]:
df.head()

,Unnamed: 0,city,country,x1,x2,x3,x4,x5,x6,x7,...,x47,x48,x49,x50,x51,x52,x53,x54,x55,data_quality
0,0,Delhi,India,4.90,22.04,4.28,1.84,3.67,1.78,0.48,...,36.26,223.87,133.38,596.16,325.82,2619.46,1068.90,586.35,7.96,1
1,1,Shanghai,China,5.59,40.51,5.59,1.12,4.19,3.96,0.52,...,121.19,1080.07,564.30,2972.57,1532.23,17333.09,9174.88,1382.83,5.01,1
2,2,Jakarta,Indonesia,2.54,22.25,3.50,2.02,3.18,2.19,0.59,...,80.32,482.85,270.15,1117.69,584.37,2694.05,1269.44,483.19,9.15,1
3,3,Manila,Philippines,3.54,27.40,3.54,1.24,1.90,2.91,0.93,...,61.82,559.52,281.78,1754.40,684.81,3536.04,2596.44,419.02,7.80,1
4,4,Seoul,South Korea,7.16,52.77,6.03,3.02,4.52,3.86,1.46,...,108.30,809.83,583.60,2621.05,1683.74,21847.94,10832.90,2672.23,3.47,1

In [3]:
df.tail()

,Unnamed: 0,city,country,x1,x2,x3,x4,x5,x6,x7,...,x47,x48,x49,x50,x51,x52,x53,x54,x55,data_quality
4869,4869,Peterborough,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4870,4870,Georgetown,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4871,4871,Ixtapa Zihuatanejo,Mexico,5.19,31.13,12.97,0.99,NaN,1.82,0.62,...,103.78,415.11,259.44,518.89,415.11,NaN,NaN,NaN,NaN,0
4872,4872,Iqaluit,Canada,29.78,74.61,13.77,6.70,8.93,3.72,3.54,...,NaN,NaN,NaN,2978.11,2978.11,NaN,NaN,NaN,6.53,0
4873,4873,Neiafu,Tonga,NaN,29.53,10.55,10.55,NaN,NaN,2.11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [4]:
df.isnull()

,Unnamed: 0,city,country,x1,x2,x3,x4,x5,x6,x7,...,x47,x48,x49,x50,x51,x52,x53,x54,x55,data_quality
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4869,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
4870,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
4871,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,True,True,True,True,False
4872,False,False,False,False,False,False,False,False,False,False,...,True,True,True,False,False,True,True,True,False,False
4873,False,False,False,True,False,False,False,True,True,False,...,True,True,True,True,True,True,True,True,True,False

In [5]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
4869    False
4870    False
4871    False
4872    False
4873    False
Length: 4874, dtype: bool

In [14]:
df.dropna()

,Unnamed: 0,city,country,x1,x2,x3,x4,x5,x6,x7,...,x47,x48,x49,x50,x51,x52,x53,x54,x55,data_quality
0,0,Delhi,India,4.90,22.04,4.28,1.84,3.67,1.78,0.48,...,36.26,223.87,133.38,596.16,325.82,2619.46,1068.90,586.35,7.96,1
1,1,Shanghai,China,5.59,40.51,5.59,1.12,4.19,3.96,0.52,...,121.19,1080.07,564.30,2972.57,1532.23,17333.09,9174.88,1382.83,5.01,1
2,2,Jakarta,Indonesia,2.54,22.25,3.50,2.02,3.18,2.19,0.59,...,80.32,482.85,270.15,1117.69,584.37,2694.05,1269.44,483.19,9.15,1
3,3,Manila,Philippines,3.54,27.40,3.54,1.24,1.90,2.91,0.93,...,61.82,559.52,281.78,1754.40,684.81,3536.04,2596.44,419.02,7.80,1
4,4,Seoul,South Korea,7.16,52.77,6.03,3.02,4.52,3.86,1.46,...,108.30,809.83,583.60,2621.05,1683.74,21847.94,10832.90,2672.23,3.47,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4727,4727,Erlenbach am Main,Germany,15.58,51.93,8.31,4.15,4.15,3.40,2.54,...,119.45,804.99,640.53,2129.33,1256.82,7042.36,4050.92,2445.27,2.35,0
4732,4732,Gig Harbor,United States,12.00,40.00,10.50,7.00,6.00,5.15,2.48,...,101.67,1800.00,2000.00,3000.00,2400.00,3821.19,2852.44,4500.00,5.22,0
4846,4846,Murovani Kurylivtsi,Ukraine,2.71,12.17,2.68,0.67,1.08,0.68,0.24,...,60.87,108.21,94.68,162.31,121.74,236.71,229.94,363.85,13.05,0
4863,4863,Tirupati,India,2.45,9.18,4.28,2.11,3.06,2.01,0.46,...,37.13,82.64,61.21,183.64,128.55,658.89,395.34,612.13,7.97,0
4867,4867,Egilsstadhir,Iceland,17.30,70.61,8.47,4.24,3.53,3.95,1.77,...,145.46,635.50,529.59,1694.68,1412.23,2012.43,1765.29,2471.40,5.00,0

In [7]:
df.isnull()

,Unnamed: 0,city,country,x1,x2,x3,x4,x5,x6,x7,...,x47,x48,x49,x50,x51,x52,x53,x54,x55,data_quality
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4869,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
4870,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
4871,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,True,True,True,True,False
4872,False,False,False,False,False,False,False,False,False,False,...,True,True,True,False,False,True,True,True,False,False
4873,False,False,False,True,False,False,False,True,True,False,...,True,True,True,True,True,True,True,True,True,False

In [23]:
df.reset_index()

,index,Unnamed: 0,city,country,x1,x2,x3,x4,x5,x6,...,x47,x48,x49,x50,x51,x52,x53,x54,x55,data_quality
0,0,0,Delhi,India,4.90,22.04,4.28,1.84,3.67,1.78,...,36.26,223.87,133.38,596.16,325.82,2619.46,1068.90,586.35,7.96,1
1,1,1,Shanghai,China,5.59,40.51,5.59,1.12,4.19,3.96,...,121.19,1080.07,564.30,2972.57,1532.23,17333.09,9174.88,1382.83,5.01,1
2,2,2,Jakarta,Indonesia,2.54,22.25,3.50,2.02,3.18,2.19,...,80.32,482.85,270.15,1117.69,584.37,2694.05,1269.44,483.19,9.15,1
3,3,3,Manila,Philippines,3.54,27.40,3.54,1.24,1.90,2.91,...,61.82,559.52,281.78,1754.40,684.81,3536.04,2596.44,419.02,7.80,1
4,4,4,Seoul,South Korea,7.16,52.77,6.03,3.02,4.52,3.86,...,108.30,809.83,583.60,2621.05,1683.74,21847.94,10832.90,2672.23,3.47,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4869,4869,4869,Peterborough,Australia,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4870,4870,4870,Georgetown,Australia,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4871,4871,4871,Ixtapa Zihuatanejo,Mexico,5.19,31.13,12.97,0.99,NaN,1.82,...,103.78,415.11,259.44,518.89,415.11,NaN,NaN,NaN,NaN,0
4872,4872,4872,Iqaluit,Canada,29.78,74.61,13.77,6.70,8.93,3.72,...,NaN,NaN,NaN,2978.11,2978.11,NaN,NaN,NaN,6.53,0
4873,4873,4873,Neiafu,Tonga,NaN,29.53,10.55,10.55,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4874 entries, 0 to 4873
Data columns (total 59 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    4874 non-null   int64
 1   city          4874 non-null   object
 2   country       4874 non-null   object
 3   x1            4449 non-null   float64
 4   x2            4432 non-null   float64
 5   x3            4552 non-null   float64
 6   x4            4385 non-null   float64
 7   x5            4445 non-null   float64
 8   x6            4540 non-null   float64
 9   x7            4438 non-null   float64
 10  x8            4571 non-null   float64
 11  x9            4494 non-null   float64
 12  x10           4457 non-null   float64
 13  x11           4538 non-null   float64
 14  x12           4369 non-null   float64
 15  x13           4393 non-null   float64
 16  x14           4318 non-null   float64
 17  x15           4312 non-null   float64
 18  x16           4509 non-null   float64
 19  x17           4499 non-null   float64
 20  x18           4439 non-null   float64
 21  x19           4410 non-null   float64
 22  x20           4444 non-null   float64
 23  x21           4447 non-null   float64
 24  x22           4379 non-null   float64
 25  x23           4490 non-null   float64
 26  x24           4414 non-null   float64
 27  x25           4149 non-null   float64
 28  x26           4223 non-null   float64
 29  x27           4389 non-null   float64
 30  x28           3401 non-null   float64
 31  x29           2750 non-null   float64
 32  x30           4013 non-null   float64
 33  x31           3869 non-null   float64
 34  x32           3506 non-null   float64
 35  x33           4296 non-null   float64
 36  x34           3839 non-null   float64
 37  x35           3904 non-null   float64
 38  x36           4400 non-null   float64
 39  x37           3702 non-null   float64
 40  x38           4534 non-null   float64
 41  x39           3523 non-null   float64
 42  x40           2508 non-null   float64
 43  x41           4405 non-null   float64
 44  x42           3761 non-null   float64
 45  x43           3230 non-null   float64
 46  x44           4413 non-null   float64
 47  x45           4273 non-null   float64
 48  x46           4388 non-null   float64
 49  x47           4337 non-null   float64
 50  x48           3533 non-null   float64
 51  x49           3465 non-null   float64
 52  x50           3418 non-null   float64
 53  x51           3385 non-null   float64
 54  x52           2681 non-null   float64
 55  x53           2609 non-null   float64
 56  x54           3459 non-null   float64
 57  x55           3894 non-null   float64
 58  data_quality  4874 non-null   int64
dtypes: float64(55), int64(2), object(2)
memory usage: 2.2+ MB

array([False, False, False, ..., False, False, False])

In [26]:
df.to_excel("Aditya.xlsx")

In [9]:
df.describe()

,Unnamed: 0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x47,x48,x49,x50,x51,x52,x53,x54,x55,data_quality
count,4874.000000,4449.000000,4432.000000,4552.000000,4385.000000,4445.000000,4540.000000,4438.000000,4571.000000,4494.000000,...,4337.000000,3533.000000,3465.000000,3418.000000,3385.000000,2681.000000,2609.000000,3459.000000,3894.000000,4874.000000
mean,2436.500000,10.321643,43.213592,6.875426,3.376732,3.937287,2.742822,1.513053,1.110768,1.139455,...,85.420108,710.696156,559.472898,1252.427627,973.603867,3207.173025,2323.089766,1817.033501,6.527214,0.186705
std,1407.146936,7.165507,25.365827,2.669017,2.080606,2.088773,1.353734,0.905525,0.749957,0.513458,...,40.328050,650.404203,529.592777,1222.803640,926.552107,6222.564176,3536.720519,1626.482870,5.423472,0.389714
min,0.000000,0.450000,3.250000,1.060000,0.320000,0.310000,0.220000,0.110000,0.070000,0.260000,...,7.570000,21.690000,12.200000,61.200000,27.110000,109.530000,48.010000,18.000000,0.600000,0.000000
25%,1218.250000,4.310000,22.350000,4.910000,1.590000,2.220000,1.560000,0.750000,0.470000,0.820000,...,57.620000,254.440000,168.970000,465.720000,325.920000,1118.030000,778.890000,478.255000,3.000000,0.000000
50%,2436.500000,9.830000,40.000000,6.960000,3.000000,3.640000,2.630000,1.450000,1.040000,1.040000,...,83.100000,519.350000,400.000000,934.000000,720.710000,2077.390000,1558.040000,1298.370000,5.210000,0.000000
75%,3654.750000,15.000000,60.000000,8.500000,5.000000,5.190000,3.722500,2.080000,1.570000,1.300000,...,106.670000,986.760000,791.670000,1700.000000,1367.330000,3782.820000,2796.500000,2742.500000,8.497500,0.000000
max,4873.000000,56.980000,211.350000,21.810000,15.000000,17.500000,10.000000,8.000000,5.770000,6.810000,...,542.740000,12608.830000,8989.370000,27006.110000,17868.180000,237522.540000,79174.180000,12681.260000,61.330000,1.000000

In [15]:
df.duplicated().sum()

0

In [16]:
df.drop_duplicates()

,Unnamed: 0,city,country,x1,x2,x3,x4,x5,x6,x7,...,x47,x48,x49,x50,x51,x52,x53,x54,x55,data_quality
0,0,Delhi,India,4.90,22.04,4.28,1.84,3.67,1.78,0.48,...,36.26,223.87,133.38,596.16,325.82,2619.46,1068.90,586.35,7.96,1
1,1,Shanghai,China,5.59,40.51,5.59,1.12,4.19,3.96,0.52,...,121.19,1080.07,564.30,2972.57,1532.23,17333.09,9174.88,1382.83,5.01,1
2,2,Jakarta,Indonesia,2.54,22.25,3.50,2.02,3.18,2.19,0.59,...,80.32,482.85,270.15,1117.69,584.37,2694.05,1269.44,483.19,9.15,1
3,3,Manila,Philippines,3.54,27.40,3.54,1.24,1.90,2.91,0.93,...,61.82,559.52,281.78,1754.40,684.81,3536.04,2596.44,419.02,7.80,1
4,4,Seoul,South Korea,7.16,52.77,6.03,3.02,4.52,3.86,1.46,...,108.30,809.83,583.60,2621.05,1683.74,21847.94,10832.90,2672.23,3.47,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4869,4869,Peterborough,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4870,4870,Georgetown,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4871,4871,Ixtapa Zihuatanejo,Mexico,5.19,31.13,12.97,0.99,NaN,1.82,0.62,...,103.78,415.11,259.44,518.89,415.11,NaN,NaN,NaN,NaN,0
4872,4872,Iqaluit,Canada,29.78,74.61,13.77,6.70,8.93,3.72,3.54,...,NaN,NaN,NaN,2978.11,2978.11,NaN,NaN,NaN,6.53,0
4873,4873,Neiafu,Tonga,NaN,29.53,10.55,10.55,NaN,NaN,2.11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [19]:
df.fillna(4)

,Unnamed: 0,city,country,x1,x2,x3,x4,x5,x6,x7,...,x47,x48,x49,x50,x51,x52,x53,x54,x55,data_quality
0,0,Delhi,India,4.90,22.04,4.28,1.84,3.67,1.78,0.48,...,36.26,223.87,133.38,596.16,325.82,2619.46,1068.90,586.35,7.96,1
1,1,Shanghai,China,5.59,40.51,5.59,1.12,4.19,3.96,0.52,...,121.19,1080.07,564.30,2972.57,1532.23,17333.09,9174.88,1382.83,5.01,1
2,2,Jakarta,Indonesia,2.54,22.25,3.50,2.02,3.18,2.19,0.59,...,80.32,482.85,270.15,1117.69,584.37,2694.05,1269.44,483.19,9.15,1
3,3,Manila,Philippines,3.54,27.40,3.54,1.24,1.90,2.91,0.93,...,61.82,559.52,281.78,1754.40,684.81,3536.04,2596.44,419.02,7.80,1
4,4,Seoul,South Korea,7.16,52.77,6.03,3.02,4.52,3.86,1.46,...,108.30,809.83,583.60,2621.05,1683.74,21847.94,10832.90,2672.23,3.47,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4869,4869,Peterborough,Australia,4.00,4.00,4.00,4.00,4.00,4.00,4.00,...,4.00,4.00,4.00,4.00,4.00,4.00,4.00,4.00,4.00,0
4870,4870,Georgetown,Australia,4.00,4.00,4.00,4.00,4.00,4.00,4.00,...,4.00,4.00,4.00,4.00,4.00,4.00,4.00,4.00,4.00,0
4871,4871,Ixtapa Zihuatanejo,Mexico,5.19,31.13,12.97,0.99,4.00,1.82,0.62,...,103.78,415.11,259.44,518.89,415.11,4.00,4.00,4.00,4.00,0
4872,4872,Iqaluit,Canada,29.78,74.61,13.77,6.70,8.93,3.72,3.54,...,4.00,4.00,4.00,2978.11,2978.11,4.00,4.00,4.00,6.53,0
4873,4873,Neiafu,Tonga,4.00,29.53,10.55,10.55,4.00,4.00,2.11,...,4.00,4.00,4.00,4.00,4.00,4.00,4.00,4.00,4.00,0

In [ ]:
index=pd.index